// fluzer create 命令 / fluzer create command
//
// 职责：从模板创建全新的 Flutter 项目
// Responsibility: create a new Flutter project from the template

import 'dart:async';
import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:mason_logger/mason_logger.dart';
import 'package:path/path.dart' as p;

import '../config/project_config.dart';
import '../templates/template_engine.dart';

/// 可注入的 flutter create 执行器，便于测试。
/// / Injectable flutter create runner for testability.
typedef CreateFlutterCreateRunner =
    Future<int> Function(
      String projectRoot, {
      String? projectName,
      String? org,
    });

/// 可注入的 flutter pub get 执行器，便于测试。
/// / Injectable flutter pub get runner for testability.
typedef CreateFlutterPubGetRunner = Future<int> Function(String projectRoot);

/// 可注入的 flutter gen-l10n 执行器，便于测试。
/// / Injectable flutter gen-l10n runner for testability.
typedef CreateFlutterGenL10nRunner = Future<int> Function(String projectRoot);

/// 可注入的 build_runner 执行器，便于测试。
/// / Injectable build_runner runner for testability.
typedef CreateBuildRunnerRunner = Future<int> Function(String projectRoot);

/// create 命令：从模板创建全新的 Flutter 项目。
///
/// 执行步骤：
/// 1. 校验项目名合法性
/// 2. 复制模板目录到目标位置
/// 3. 全局替换包名（flutter_zero_template → 项目名）
/// 4. 重命名 .iml 文件
/// 5. 执行 flutter create . --org --project-name
/// 6. 清理 flutter create 生成的多余测试文件
/// 7. 执行 flutter pub get
/// 8. 执行 flutter gen-l10n
/// 9. 执行 build_runner（可选）
///
///
/// create command: creates a new Flutter project from the template.
///
/// Steps:
/// 1. Validate project name
/// 2. Copy template directory to target location
/// 3. Global package name replacement
/// 4. Rename .iml file
/// 5. Run flutter create . --org --project-name
/// 6. Clean up extra test files generated by flutter create
/// 7. Run flutter pub get
/// 8. Run flutter gen-l10n
/// 9. Run build_runner (optional)
class CreateCommand extends Command<int> {
  /// 创建 CreateCommand 实例。
  ///
  /// 所有执行器均可注入，便于测试。
  ///
  /// Creates a CreateCommand instance.
  ///
  /// All runners are injectable for testability.
  CreateCommand({
    Logger? logger,
    this._templatesDir,
    CreateFlutterCreateRunner? flutterCreate,
    CreateFlutterPubGetRunner? flutterPubGet,
    CreateFlutterGenL10nRunner? flutterGenL10n,
    CreateBuildRunnerRunner? buildRunner,
  }) : _logger = logger ?? Logger(),
       _flutterCreate = flutterCreate ?? _defaultFlutterCreate,
       _flutterPubGet = flutterPubGet ?? _defaultFlutterPubGet,
       _flutterGenL10n = flutterGenL10n ?? _defaultFlutterGenL10n,
       _buildRunner = buildRunner ?? _defaultBuildRunner {
    argParser.addOption(
      'org',
      defaultsTo: 'com.example',
      help: '组织标识（影响 bundle ID） / Organization identifier (affects bundle ID)',
    );
    argParser.addOption('desc', help: '项目描述 / Project description');
    argParser.addFlag(
      'build-runner',
      defaultsTo: true,
      negatable: true,
      help: '是否运行 build_runner / Whether to run build_runner after creation',
    );
  }

  final Logger _logger;
  final Directory? _templatesDir;
  final CreateFlutterCreateRunner _flutterCreate;
  final CreateFlutterPubGetRunner _flutterPubGet;
  final CreateFlutterGenL10nRunner _flutterGenL10n;
  final CreateBuildRunnerRunner _buildRunner;

  /// 模板中的默认包名，需要被替换的目标字符串。
  ///
  /// The default package name in the template that needs to be replaced.
  static const String _templatePackageName = 'flutter_zero_template';

  @override
  String get name => 'create';

  @override
  String get description =>
      '从模板创建全新 Flutter 项目 / Create a new Flutter project from the template';

  @override
  String get invocation => 'fluzer create <project_name>';

  @override
  Future<int> run() async {
    final projectName = argResults?.rest.firstOrNull;
    if (projectName == null) {
      _logger.err('错误：请指定项目名 / Error: please specify a project name');
      printUsage();
      return 1;
    }

    // 校验项目名合法性
    if (!_isValidProjectName(projectName)) {
      _logger.err(
        '项目名不合法：必须只包含小写字母、数字和下划线，且以字母开头。\n'
        'Invalid project name: must contain only lowercase letters, digits, '
        'and underscores, starting with a letter.',
      );
      return 1;
    }

    final org = argResults!['org'] as String;
    final desc = argResults!['desc'] as String?;
    final runBuildRunner = argResults!['build-runner'] as bool;

    // 目标目录 = 当前工作目录 + 项目名
    final targetDir = p.join(Directory.current.path, projectName);

    try {
      _step('步骤 1/9：校验项目名 ...');
      _logger.detail('  项目名: $projectName, 组织: $org');

      // 检查目标目录是否已存在
      if (Directory(targetDir).existsSync()) {
        throw CliException(
          '目录 $projectName 已存在，请选择不同的项目名。\n'
          'Directory $projectName already exists. '
          'Please choose a different project name.',
        );
      }

      _step('步骤 2/9：复制模板文件 ...');
      final templatesDir =
          _templatesDir ??
          await TemplateEngine.resolvePackageTemplatesDirectory();
      final projectTemplateDir = Directory(
        p.join(templatesDir.path, 'project'),
      );
      if (!projectTemplateDir.existsSync()) {
        throw CliException(
          '模板项目目录不存在: ${projectTemplateDir.path}\n'
          'Template project directory not found: ${projectTemplateDir.path}',
        );
      }
      _copyDirectory(projectTemplateDir, Directory(targetDir));
      _logger.detail('  已复制 ${projectTemplateDir.path} → $targetDir');

      _step('步骤 3/9：全局替换包名 ...');
      final replacedCount = _replacePackageName(targetDir, projectName);
      _logger.detail('  已替换 $replacedCount 处包名引用');

      _step('步骤 4/9：重命名 .iml 文件 ...');
      _renameImlFile(targetDir, projectName);

      // 可选：替换项目描述
      if (desc != null) {
        _replaceDescription(targetDir, desc);
      }

      _step('步骤 5/9：执行 flutter create . ...');
      final createExitCode = await _flutterCreate(
        targetDir,
        projectName: projectName,
        org: org,
      );
      if (createExitCode != 0) {
        throw CliException(
          'flutter create 执行失败 (exit code: $createExitCode)\n'
          'flutter create failed (exit code: $createExitCode)',
        );
      }

      _step('步骤 6/9：清理 flutter create 生成的多余测试文件 ...');
      _cleanTests(targetDir);

      _step('步骤 7/9：执行 flutter pub get ...');
      final pubGetExitCode = await _flutterPubGet(targetDir);
      if (pubGetExitCode != 0) {
        throw CliException(
          'flutter pub get 执行失败 (exit code: $pubGetExitCode)\n'
          'flutter pub get failed (exit code: $pubGetExitCode)',
        );
      }

      _step('步骤 8/9：执行 flutter gen-l10n ...');
      final genL10nExitCode = await _flutterGenL10n(targetDir);
      if (genL10nExitCode != 0) {
        throw CliException(
          'flutter gen-l10n 执行失败 (exit code: $genL10nExitCode)\n'
          'flutter gen-l10n failed (exit code: $genL10nExitCode)',
        );
      }

      _step('步骤 9/9：执行 build_runner ...');
      if (runBuildRunner) {
        final brExitCode = await _buildRunner(targetDir);
        if (brExitCode != 0) {
          _logger.warn(
            'build_runner 执行失败 (exit code: $brExitCode)，'
            '项目已创建，可手动运行。\n'
            'build_runner failed; project created. '
            'You can run it manually.',
          );
        }
      } else {
        _logger.info(
          '跳过 build_runner，可手动运行：\n'
          'Skipped build_runner; run it manually:\n'
          '  dart run build_runner build --delete-conflicting-outputs',
        );
      }

      _done(targetDir, projectName);
      return 0;
    } on CliException catch (e) {
      _logger.err(e.message);
      // 清理失败的目录
      _cleanupOnFailure(targetDir);
      return 1;
    } on ProcessException catch (e) {
      _logger.err(
        '未找到 Flutter 命令。请确保 Flutter SDK 已正确安装并在 PATH 中。\n'
        'Flutter command not found. Make sure Flutter SDK is installed and in PATH.\n'
        '原始错误 / Original error: ${e.message}',
      );
      _cleanupOnFailure(targetDir);
      return 1;
    } on Object catch (e) {
      _logger.err('创建失败 / Creation failed: $e');
      _cleanupOnFailure(targetDir);
      return 1;
    }
  }

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  /// 校验项目名是否合法（小写字母开头，只含小写字母、数字和下划线）。
  ///
  /// Validates that a project name is legal (starts with a lowercase letter,
  /// contains only lowercase letters, digits, and underscores).
  bool _isValidProjectName(String name) {
    final regex = RegExp(r'^[a-z][a-z0-9_]*$');
    return regex.hasMatch(name);
  }

  /// 打印步骤标题 / Prints a step header
  void _step(String message) {
    _logger.info('\n$message');
  }

  /// 打印完成信息 / Prints completion message
  void _done(String targetDir, String projectName) {
    _logger.success('\n项目创建完成！ / Project created successfully!');
    _logger.info('');
    _logger.info('后续步骤 / Next steps:');
    _logger.info('  1. cd $projectName');
    _logger.info('  2. fluzer new my_feature （可选：添加功能模块）');
    _logger.info('  3. flutter run           （启动应用）');
  }

  /// 递归复制目录（排除 .dart_tool、build、.idea）。
  ///
  /// Recursively copies a directory (excluding .dart_tool, build, .idea).
  void _copyDirectory(Directory source, Directory target) {
    if (!target.existsSync()) {
      target.createSync(recursive: true);
    }

    for (final entity in source.listSync()) {
      final relativePath = p.relative(entity.path, from: source.path);
      final targetPath = p.join(target.path, relativePath);

      if (entity is Directory) {
        // 排除构建产物目录
        final dirName = p.basename(entity.path);
        if (const {
          'l10n_gen',
          '.dart_tool',
          'build',
          '.idea',
        }.contains(dirName)) {
          continue;
        }
        _copyDirectory(entity, Directory(targetPath));
      } else if (entity is File) {
        // 排除 pubspec.lock（会由 pub get 重新生成）
        if (p.basename(entity.path) == 'pubspec.lock') continue;
        File(targetPath).writeAsBytesSync(entity.readAsBytesSync());
      }
    }
  }

  /// 清理 flutter create 生成的多余测试文件。
  ///
  /// `flutter create .` 会自动在 test/ 目录下生成一个默认的
  /// `widget_test.dart`，但模板项目已自带了 `home_page_test.dart`，
  /// 该默认测试文件需要删除。
  ///
  /// Cleans up extra test files generated by `flutter create .`.
  ///
  /// `flutter create .` auto-generates a default `widget_test.dart`
  /// in the test/ directory, but the template already includes
  /// `home_page_test.dart`. This default test file should be removed.
  void _cleanTests(String targetDir) {
    final widgetTest = File(p.join(targetDir, 'test', 'widget_test.dart'));
    if (widgetTest.existsSync()) {
      widgetTest.deleteSync();
      _logger.detail('  已删除 / Removed: test/widget_test.dart');
    }
  }

  /// 全局替换包名：将所有文本文件中的 `flutter_zero_template` 替换为新包名。
  ///
  /// Global package name replacement: replaces `flutter_zero_template`
  /// in all text files with the new package name.
  int _replacePackageName(String targetDir, String newName) {
    var count = 0;
    final dir = Directory(targetDir);

    for (final entity in dir.listSync(recursive: true)) {
      if (entity is File && _isTextFile(entity.path)) {
        var content = entity.readAsStringSync();
        if (content.contains(_templatePackageName)) {
          content = content.replaceAll(_templatePackageName, newName);
          entity.writeAsStringSync(content);
          count++;
        }
      }
    }
    return count;
  }

  /// 判断文件是否为文本文件（可做字符串替换）。
  ///
  /// Determines if a file is a text file (eligible for string replacement).
  bool _isTextFile(String path) {
    const textExtensions = {
      '.dart',
      '.yaml',
      '.arb',
      '.md',
      '.json',
      '.xml',
      '.gitignore',
      '.iml',
      '.txt',
      '.cfg',
      '.toml',
    };
    final ext = p.extension(path);
    final basename = p.basename(path);
    // 特殊文件：.gitignore、.metadata 等无扩展名
    if (const {'.gitignore', '.metadata'}.contains(basename)) return true;
    return textExtensions.contains(ext);
  }

  /// 重命名 .iml 文件：`flutter_zero_template.iml` → `<newName>.iml`。
  ///
  /// Renames the .iml file: `flutter_zero_template.iml` → `<newName>.iml`.
  void _renameImlFile(String targetDir, String newName) {
    final oldIml = File(p.join(targetDir, '$_templatePackageName.iml'));
    if (oldIml.existsSync()) {
      final newIml = File(p.join(targetDir, '$newName.iml'));
      oldIml.renameSync(newIml.path);
      _logger.detail('  $_templatePackageName.iml → $newName.iml');
    }
  }

  /// 替换 pubspec.yaml 中的 description 字段。
  ///
  /// Replaces the description field in pubspec.yaml.
  void _replaceDescription(String targetDir, String desc) {
    final pubspec = File(p.join(targetDir, 'pubspec.yaml'));
    if (!pubspec.existsSync()) return;

    var content = pubspec.readAsStringSync();
    // 替换 description 行
    final descRegex = RegExp(r'^description:\s*".*"$', multiLine: true);
    content = content.replaceFirst(descRegex, 'description: "$desc"');
    pubspec.writeAsStringSync(content);
  }

  /// 创建失败时清理目标目录。
  ///
  /// Cleans up the target directory on failure.
  void _cleanupOnFailure(String targetDir) {
    final dir = Directory(targetDir);
    if (dir.existsSync()) {
      try {
        dir.deleteSync(recursive: true);
        _logger.detail('  已清理失败目录 / Cleaned up failed directory');
      } on Object {
        // 清理失败不影响错误报告
      }
    }
  }

  // ---------------------------------------------------------------------------
  // Default runners
  // ---------------------------------------------------------------------------

  /// 默认的 flutter create 执行器 / Default flutter create runner
  static Future<int> _defaultFlutterCreate(
    String projectRoot, {
    String? projectName,
    String? org,
  }) async {
    final args = ['create', '.'];
    if (projectName != null) {
      args.addAll(['--project-name', projectName]);
    }
    if (org != null) {
      args.addAll(['--org', org]);
    }

    final process = await Process.start(
      'flutter',
      args,
      workingDirectory: projectRoot,
      runInShell: true,
    );

    unawaited(
      process.stdout
          .transform(const SystemEncoding().decoder)
          .forEach(stdout.write),
    );
    unawaited(
      process.stderr
          .transform(const SystemEncoding().decoder)
          .forEach(stderr.write),
    );

    return process.exitCode;
  }

  /// 默认的 flutter pub get 执行器 / Default flutter pub get runner
  static Future<int> _defaultFlutterPubGet(String projectRoot) async {
    final process = await Process.start(
      'flutter',
      ['pub', 'get'],
      workingDirectory: projectRoot,
      runInShell: true,
    );

    unawaited(
      process.stdout
          .transform(const SystemEncoding().decoder)
          .forEach(stdout.write),
    );
    unawaited(
      process.stderr
          .transform(const SystemEncoding().decoder)
          .forEach(stderr.write),
    );

    return process.exitCode;
  }

  /// 默认的 flutter gen-l10n 执行器 / Default flutter gen-l10n runner
  static Future<int> _defaultFlutterGenL10n(String projectRoot) async {
    final process = await Process.start(
      'flutter',
      ['gen-l10n'],
      workingDirectory: projectRoot,
      runInShell: true,
    );

    unawaited(
      process.stdout
          .transform(const SystemEncoding().decoder)
          .forEach(stdout.write),
    );
    unawaited(
      process.stderr
          .transform(const SystemEncoding().decoder)
          .forEach(stderr.write),
    );

    return process.exitCode;
  }

  /// 默认的 build_runner 执行器 / Default build_runner runner
  static Future<int> _defaultBuildRunner(String projectRoot) async {
    final process = await Process.start(
      'dart',
      ['run', 'build_runner', 'build', '--delete-conflicting-outputs'],
      workingDirectory: projectRoot,
      runInShell: true,
    );

    unawaited(
      process.stdout
          .transform(const SystemEncoding().decoder)
          .forEach(stdout.write),
    );
    unawaited(
      process.stderr
          .transform(const SystemEncoding().decoder)
          .forEach(stderr.write),
    );

    return process.exitCode;
  }
}
