// fluzer create 命令 / fluzer create command
//
// 职责：从模板创建全新的 Flutter 项目
// Responsibility: create a new Flutter project from the template

import 'dart:io';

import 'package:args/command_runner.dart';
import 'package:fluzer/src/i18n/gen/strings.g.dart';
import 'package:mason_logger/mason_logger.dart';
import 'package:path/path.dart' as p;

import '../config/project_config.dart';
import '../logging/spinner.dart';
import '../process/process_runner.dart';
import '../template/brick_loader.dart';
import '../template/brick_renderer.dart';
import '../template/template_source.dart';
import '../version/version_check.dart';
import '../version/version_check_mixin.dart';

/// 可注入的 flutter create 执行器，便于测试。
/// / Injectable flutter create runner for testability.
typedef CreateFlutterCreateRunner =
    Future<int> Function(
      String projectRoot, {
      String? projectName,
      String? org,
    });

/// 可注入的 flutter pub get 执行器，便于测试。
/// / Injectable flutter pub get runner for testability.
typedef CreateFlutterPubGetRunner = Future<int> Function(String projectRoot);

/// 可注入的 flutter gen-l10n 执行器，便于测试。
/// / Injectable flutter gen-l10n runner for testability.
typedef CreateFlutterGenL10nRunner = Future<int> Function(String projectRoot);

/// create 命令：从模板创建全新的 Flutter 项目。
///
/// 执行步骤：
/// 1. 校验项目名合法性
/// 2. 用 Mason 渲染 project brick 到当前目录（brick 的 `{{name}}` 层即目标项目目录）
/// 3. 执行 flutter create . --org --project-name
/// 4. 清理 flutter create 生成的多余测试文件
/// 5. 执行 flutter pub get
/// 6. 执行 flutter gen-l10n
///
/// create command: creates a new Flutter project from the template.
///
/// Steps:
/// 1. Validate project name
/// 2. Render the project brick via Mason into cwd (the brick's `{{name}}`
///    layer becomes the target project dir)
/// 3. Run flutter create . --org --project-name
/// 4. Clean up extra test files generated by flutter create
/// 5. Run flutter pub get
/// 6. Run flutter gen-l10n
class CreateCommand extends Command<int> with VersionCheckMixin {
  /// 创建 CreateCommand 实例。
  ///
  /// 所有执行器与 [loader] 均可注入，便于测试。
  ///
  /// Creates a CreateCommand instance.
  ///
  /// All runners and [loader] are injectable for testability.
  CreateCommand({
    Logger? logger,
    BrickLoader? loader,
    CreateFlutterCreateRunner? flutterCreate,
    CreateFlutterPubGetRunner? flutterPubGet,
    CreateFlutterGenL10nRunner? flutterGenL10n,
    this.workingDirectory,
    VersionCheckService? versionCheckService,
    ProcessRunner? processRunner,
    Translations? messages,
  }) : _logger = logger ?? Logger(),
       // ignore: prefer_initializing_formals
       _loader = loader,
       _messages = messages ?? AppLocale.zh.buildSync(),
       _versionCheckService =
           versionCheckService ??
           VersionCheckService(
             logger: logger ?? Logger(),
             messages: messages ?? AppLocale.zh.buildSync(),
           ),
       _processRunner = processRunner ?? ProcessRunner() {
    _flutterCreate = flutterCreate ?? _defaultFlutterCreate;
    _flutterPubGet = flutterPubGet ?? _defaultFlutterPubGet;
    _flutterGenL10n = flutterGenL10n ?? _defaultFlutterGenL10n;
    argParser.addOption(
      'org',
      defaultsTo: 'com.example',
      help: _messages.create.orgHelp,
    );
  }

  final Logger _logger;
  final BrickLoader? _loader;
  final Translations _messages;

  /// 注入的版本检查服务（测试用）；省略时创建默认实例。
  ///
  /// Injected version-check service (for tests); creates a default instance
  /// when omitted.
  final VersionCheckService _versionCheckService;

  final ProcessRunner _processRunner;

  @override
  Logger get logger => _logger;

  @override
  Translations get messages => _messages;

  @override
  VersionCheckService get versionCheckService => _versionCheckService;

  /// 工作目录（渲染输出与拼接目标目录的基准）。
  /// 省略时回退到当前工作目录。测试注入临时目录以避免依赖全局 cwd。
  ///
  /// Working directory (base for rendering output and the target dir).
  /// Defaults to the current directory; tests inject a temp dir to avoid
  /// mutating the global cwd.
  final Directory? workingDirectory;
  late final CreateFlutterCreateRunner _flutterCreate;
  late final CreateFlutterPubGetRunner _flutterPubGet;
  late final CreateFlutterGenL10nRunner _flutterGenL10n;

  @override
  String get name => 'create';

  @override
  String get description => _messages.create.description;

  @override
  String get invocation => 'fluzer create <project_name>';

  @override
  Future<int> run() async {
    // 启动版本检查提示（缓存命中瞬时提示，缓存未命中以 spinner 包裹网络等待）；
    // 无更新 / 网络异常静默降级，不阻断主流程。
    await ensureUpdateNotified();

    final projectName = argResults?.rest.firstOrNull;
    if (projectName == null) {
      _logger.err(_messages.create.nameRequired);
      printUsage();
      return 1;
    }

    // 校验项目名合法性
    if (!_isValidProjectName(projectName)) {
      _logger.err(_messages.create.nameInvalid);
      return 1;
    }

    final org = argResults!['org'] as String;

    // 目标目录 = 工作目录 + 项目名（即 Mason 渲染出的 {{name}} 目录）
    final baseDir = workingDirectory?.path ?? Directory.current.path;
    final targetDir = p.join(baseDir, projectName);

    try {
      // 每一步骤都用 runWithSpinner 给出「正在执行」的旋转反馈；
      // --log（verbose）模式下由 logger.level 控制不显示 spinner，过程靠日志展示。
      // work 内部只用 detail（非 verbose 下被抑制），避免破坏 spinner 行。
      await runWithSpinner(
        logger: _logger,
        messages: _messages,
        message: _messages.create.step1Validate,
        work: () async {
          if (!_isValidProjectName(projectName)) {
            throw CliException(_messages.create.nameInvalid);
          }
          _logger.detail(
            _messages.create.detailProject(name: projectName, org: org),
          );
          // 检查目标目录是否已存在。
          // 此处必须抛 DirExistsException 而非 CliException：
          // 该目录是用户既有数据，捕获方据此跳过清理，绝不删除它。
          // 后续若新增「跳过存在性检查」的选项（如 --force），
          // 需同步确认清理路径不会误删用户原有目录。
          if (Directory(targetDir).existsSync()) {
            throw DirExistsException(
              _messages.create.dirExists(name: projectName),
            );
          }
        },
      );

      await runWithSpinner(
        logger: _logger,
        messages: _messages,
        message: _messages.create.step2Render,
        work: () async {
          // 直接渲染到当前目录：brick 的 {{name}} 层展开后即为 targetDir
          final brickLoader =
              _loader ??
              await TemplateSourceResolver(
                logger: _logger,
                messages: _messages,
              ).resolve();
          final renderer = BrickRenderer(brickLoader);
          await renderer.generate(
            brickName: 'project',
            outputDir: workingDirectory ?? Directory.current,
            vars: {'name': projectName},
          );
          _logger.detail(_messages.create.detailGenerated(path: targetDir));
        },
      );

      await _runOrThrow(
        _messages.create.step3FlutterCreate,
        () => _flutterCreate(targetDir, projectName: projectName, org: org),
      );

      await runWithSpinner(
        logger: _logger,
        messages: _messages,
        message: _messages.create.step4CleanTest,
        work: () async {
          _cleanTests(targetDir);
        },
      );

      await _runOrThrow(
        _messages.create.step5PubGet,
        () => _flutterPubGet(targetDir),
      );

      await _runOrThrow(
        _messages.create.step6GenL10n,
        () => _flutterGenL10n(targetDir),
      );

      _done(targetDir, projectName);
      return 0;
    } on DirExistsException catch (e) {
      // 目标目录是用户既有数据，不属于本次命令创建：只报错，绝不清理。
      // 该 catch 必须位于 CliException 之前，否则会被父类分支吞掉。
      _logger.err(e.message);
      return 1;
    } on CliException catch (e) {
      _logger.err(e.message);
      // 清理本次命令创建的半成品目录
      _cleanupOnFailure(targetDir);
      return 1;
    } on ProcessException catch (e) {
      _logger.err(_messages.create.flutterNotFound(error: e.message));
      _cleanupOnFailure(targetDir);
      return 1;
    } on Object catch (e) {
      _logger.err(_messages.create.failed(error: e));
      _cleanupOnFailure(targetDir);
      return 1;
    }
  }

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  /// 执行步骤命令并在非零退出码时抛出 [CliException]。
  ///
  /// [step] 为步骤名（自动拼入中英文错误信息），[runner] 为返回退出码的闭包
  /// （用闭包吞掉各 runner 签名差异，如 `flutter create` 额外带 name/org）。
  ///
  /// Runs a step command and throws [CliException] on a non-zero exit code.
  Future<void> _runOrThrow(String step, Future<int> Function() runner) async {
    final code = await runWithSpinner(
      logger: _logger,
      messages: _messages,
      message: step,
      work: runner,
    );
    if (code != 0) {
      throw CliException(
        _messages.create.stepFailedWithCode(step: step, code: code),
      );
    }
  }

  /// 校验项目名是否合法（小写字母开头，只含小写字母、数字和下划线）。
  ///
  /// Validates that a project name is legal (starts with a lowercase letter,
  /// contains only lowercase letters, digits, and underscores).
  bool _isValidProjectName(String name) {
    final regex = RegExp(r'^[a-z][a-z0-9_]*$');
    return regex.hasMatch(name);
  }

  /// 打印完成信息 / Prints completion message
  void _done(String targetDir, String projectName) {
    _logger.success(_messages.create.created);
    _logger.info('');
    _logger.info(_messages.create.nextSteps);
    _logger.info('  1. cd $projectName');
    _logger.info(_messages.create.stepNewFeature);
    _logger.info(_messages.create.stepFlutterRun);
  }

  /// 清理 flutter create 生成的多余测试文件。
  ///
  /// `flutter create .` 会自动在 test/ 目录下生成一个默认的
  /// `widget_test.dart`，但模板项目已自带了 `home_page_test.dart`，
  /// 该默认测试文件需要删除。
  ///
  /// Cleans up extra test files generated by `flutter create .`.
  ///
  /// `flutter create .` auto-generates a default `widget_test.dart`
  /// in the test/ directory, but the template already includes
  /// `home_page_test.dart`. This default test file should be removed.
  void _cleanTests(String targetDir) {
    final widgetTest = File(p.join(targetDir, 'test', 'widget_test.dart'));
    if (widgetTest.existsSync()) {
      try {
        widgetTest.deleteSync();
        _logger.detail(_messages.create.removedWidgetTest);
      } on Object catch (e) {
        _logger.detail(_messages.create.removeWidgetTestFailed(error: e));
      }
    }
  }

  /// 删除 [targetDir]（目录不存在时静默跳过，删除失败只记日志不抛出）。
  ///
  /// 职责单一：只做删除，不判断该不该删。
  /// **是否有权删除由调用方决定** —— 仅当目录确认为本次命令创建的半成品时
  /// 才可调用；用户既有目录的场景由 [DirExistsException] 分支拦截，不会走到这里。
  ///
  /// Deletes [targetDir] (silently skips when absent, logs deletion failures).
  ///
  /// Single responsibility: it only deletes and never decides whether deletion
  /// is allowed. Callers must ensure the directory was created by this run;
  /// pre-existing user directories are handled by the [DirExistsException]
  /// branch and never reach this method.
  void _cleanupOnFailure(String targetDir) {
    final dir = Directory(targetDir);
    if (dir.existsSync()) {
      try {
        dir.deleteSync(recursive: true);
        _logger.detail(_messages.create.cleanedFailedDir);
      } on Object catch (e) {
        _logger.detail(_messages.create.cleanupFailedDir(error: e));
      }
    }
  }

  // ---------------------------------------------------------------------------
  // Default runners
  // ---------------------------------------------------------------------------

  /// 默认的 flutter create 执行器 / Default flutter create runner
  Future<int> _defaultFlutterCreate(
    String projectRoot, {
    String? projectName,
    String? org,
  }) {
    final args = ['create', '.'];
    if (projectName != null) {
      args.addAll(['--project-name', projectName]);
    }
    if (org != null) {
      args.addAll(['--org', org]);
    }
    return _processRunner.run(
      'flutter',
      args,
      workingDirectory: projectRoot,
      showLive: _logger.level == Level.verbose,
      runInShell: true,
    );
  }

  /// 默认的 flutter pub get 执行器 / Default flutter pub get runner
  Future<int> _defaultFlutterPubGet(String projectRoot) {
    return _processRunner.run(
      'flutter',
      ['pub', 'get'],
      workingDirectory: projectRoot,
      showLive: _logger.level == Level.verbose,
      runInShell: true,
    );
  }

  /// 默认的 flutter gen-l10n 执行器 / Default flutter gen-l10n runner
  Future<int> _defaultFlutterGenL10n(String projectRoot) {
    return _processRunner.run(
      'flutter',
      ['gen-l10n'],
      workingDirectory: projectRoot,
      showLive: _logger.level == Level.verbose,
      runInShell: true,
    );
  }
}
