// fluzer create 命令 / fluzer create command
//
// 职责：从模板创建全新的 Flutter 项目
// Responsibility: create a new Flutter project from the template

import 'dart:io';

import 'package:args/args.dart';
import 'package:mason_logger/mason_logger.dart';
import 'package:path/path.dart' as p;

import '../../commands/base_command.dart';
import '../../commands/create/create_context.dart';
import '../../config/project_config.dart';
import '../../process/process_runner.dart';
import '../../template/brick_loader.dart';
import '../../template/brick_renderer.dart';
import '../../template/template_source.dart';
import '../../util/step_runner.dart';
import '../../version/version_update_notifier.dart';

/// create 命令：从模板创建全新的 Flutter 项目。
///
/// 执行步骤：
/// 1. 校验项目名合法性
/// 2. 用 Mason 渲染 project brick 到当前目录（brick 的 `{{name}}` 层即目标项目目录）
/// 3. 执行 flutter create . --org --project-name
/// 4. 清理 flutter create 生成的多余测试文件
/// 5. 执行 flutter pub get
/// 6. 执行 flutter gen-l10n
///
/// create command: creates a new Flutter project from the template.
///
/// Steps:
/// 1. Validate project name
/// 2. Render the project brick via Mason into cwd (the brick's `{{name}}`
///    layer becomes the target project dir)
/// 3. Run flutter create . --org --project-name
/// 4. Clean up extra test files generated by flutter create
/// 5. Run flutter pub get
/// 6. Run flutter gen-l10n
class CreateCommand extends BaseCommand<CreateCommandContext> {
  /// 创建 CreateCommand 实例。
  ///
  /// [logger] / [translations] / [versionCheckService] / [processRunner] 由外部
  /// 必填注入（[Fluzer] 统一提供）；各 flutter 执行器与 [loader] 可选注入，便于测试。
  ///
  /// Creates a CreateCommand instance.
  ///
  /// [logger] / [translations] / [versionCheckService] / [processRunner] are
  /// required (injected by [Fluzer]); the flutter runners and [loader] are
  /// optional for testability.
  CreateCommand({
    required super.logger,
    this._loader,
    super.workingDirectory,
    required super.versionCheckService,
    required this.processRunner,
    required super.translations,
  }) {
    argParser.addOption(
      'org',
      defaultsTo: 'com.example',
      help: translations.create.orgHelp,
    );
  }

  final BrickLoader? _loader;

  /// 注入的进程执行器；省略时使用默认实现。
  ///
  /// Injected process runner; uses the default implementation when omitted.
  final ProcessRunner processRunner;

  @override
  String get name => 'create';

  @override
  String get description => translations.create.description;

  @override
  String get invocation => 'fluzer create <project_name>';

  @override
  Future<CreateCommandContext> buildContext(ArgResults args) async {
    final projectName = args.rest.firstOrNull ?? '';
    final org = args['org'] as String;
    final baseDir = workingDirectory?.path ?? Directory.current.path;
    final targetDir = p.join(baseDir, projectName);
    return CreateCommandContext(
      workingDirectory: workingDirectory,
      projectName: projectName,
      org: org,
      targetDir: targetDir,
    );
  }

  @override
  Future<int> execute(CreateCommandContext ctx) async {
    // 启动版本检查提示（create 命令显式 opt-in；缓存命中瞬时提示，
    // 缓存未命中以 spinner 包裹网络等待；无更新 / 网络异常静默降级，不阻断主流程）。

    final projectName = ctx.projectName;
    if (projectName.isEmpty) {
      logger.err(translations.create.nameRequired);
      printUsage();
      return 1;
    }

    // 校验项目名合法性
    if (!_isValidProjectName(projectName)) {
      logger.err(translations.create.nameInvalid);
      return 1;
    }

    final org = ctx.org;
    final targetDir = ctx.targetDir;

    final steps = StepRunner(logger: logger, translations: translations);


    await VersionUpdateNotifier(
      logger: logger,
      translations: translations,
      versionCheckService: versionCheckService,
    ).notify(steps);

    // 1. 校验项目名与目录
    steps.add(translations.create.step1Validate, () async {
      if (!_isValidProjectName(projectName)) {
        throw CliException(translations.create.nameInvalid);
      }
      logger.detail(
        translations.create.detailProject(name: projectName, org: org),
      );
      // 检查目标目录是否已存在。
      // 此处必须抛 DirExistsException 而非 CliException：
      // 该目录是用户既有数据，捕获方据此跳过清理，绝不删除它。
      // 后续若新增「跳过存在性检查」的选项（如 --force），
      // 需同步确认清理路径不会误删用户原有目录。
      if (await Directory(targetDir).exists()) {
        throw DirExistsException(
          translations.create.dirExists(name: projectName),
        );
      }
    });

    // 2. 渲染 project 模板（brick 的 {{name}} 层展开后即 targetDir）
    steps.add(translations.create.step2Render, () async {
      final brickLoader =
          _loader ??
          await TemplateSourceResolver(
            logger: logger,
            messages: translations,
          ).resolve();
      final renderer = BrickRenderer(brickLoader);
      await renderer.generate(
        brickName: 'project',
        outputDir: workingDirectory ?? Directory.current,
        vars: {'name': projectName},
      );
      logger.detail(translations.create.detailGenerated(path: targetDir));
    });

    // 3. 执行 flutter create .（子命令非零退出码时在 work 内部抛异常）
    final step3 = translations.create.step3FlutterCreate;
    steps.add(
      step3,
      () => _throwIfNonZero(
        step3,
        () => _flutterCreate(targetDir, projectName: projectName, org: org),
      ),
    );

    // 4. 清理 flutter create 生成的多余测试文件
    steps.add(translations.create.step4CleanTest, () async {
      await _cleanTests(targetDir);
    });

    // 5. 执行 flutter pub get
    final step5 = translations.create.step5PubGet;
    steps.add(
      step5,
      () => _throwIfNonZero(step5, () => _flutterPubGet(targetDir)),
    );

    // 6. 执行 flutter gen-l10n
    final step6 = translations.create.step6GenL10n;
    steps.add(
      step6,
      () => _throwIfNonZero(step6, () => _flutterGenL10n(targetDir)),
    );

    try {
      await steps.runAll();
      _done(targetDir, projectName);
      return 0;
    } on DirExistsException catch (e) {
      // 目标目录是用户既有数据，不属于本次命令创建：只报错，绝不清理。
      // 该 catch 必须位于 CliException 之前，否则会被父类分支吞掉。
      logger.err(e.message);
      return 1;
    } on CliException catch (e) {
      logger.err(e.message);
      // 清理本次命令创建的半成品目录
      await _cleanupOnFailure(targetDir);
      return 1;
    } on ProcessException catch (e) {
      logger.err(translations.create.flutterNotFound(error: e.message));
      await _cleanupOnFailure(targetDir);
      return 1;
    } on Object catch (e) {
      logger.err(translations.create.failed(error: e));
      await _cleanupOnFailure(targetDir);
      return 1;
    }
  }

  // ---------------------------------------------------------------------------
  // Helpers
  // ---------------------------------------------------------------------------

  /// 运行返回退出码的子命令，非零则抛 [CliException]。
  ///
  /// 用于在 [StepRunner] 步骤的 [work] 内部统一处理子命令退出码；异常会中断
  /// 后续步骤并向上冒泡到 [execute] 的 catch 分支做清理。
  ///
  /// [step] 为步骤描述（拼入中英文错误信息），[runner] 为返回退出码的闭包
  /// （用闭包吞掉各 runner 签名差异，如 `flutter create` 额外带 name/org）。
  Future<void> _throwIfNonZero(
    String step,
    Future<int> Function() runner,
  ) async {
    final code = await runner();
    if (code != 0) {
      throw CliException(
        translations.create.stepFailedWithCode(step: step, code: code),
      );
    }
  }

  /// 校验项目名是否合法（小写字母开头，只含小写字母、数字和下划线）。
  ///
  /// Validates that a project name is legal (starts with a lowercase letter,
  /// contains only lowercase letters, digits, and underscores).
  bool _isValidProjectName(String name) {
    final regex = RegExp(r'^[a-z][a-z0-9_]*$');
    return regex.hasMatch(name);
  }

  /// 打印完成信息 / Prints completion message
  void _done(String targetDir, String projectName) {
    logger.success(translations.create.created);
    logger.info('');
    logger.info(translations.create.nextSteps);
    logger.info('  1. cd $projectName');
    logger.info(translations.create.stepNewFeature);
    logger.info(translations.create.stepFlutterRun);
  }

  /// 清理 flutter create 生成的多余测试文件。
  ///
  /// `flutter create .` 会自动在 test/ 目录下生成一个默认的
  /// `widget_test.dart`，但模板项目已自带了 `home_page_test.dart`，
  /// 该默认测试文件需要删除。
  ///
  /// Cleans up extra test files generated by `flutter create .`.
  ///
  /// `flutter create .` auto-generates a default `widget_test.dart`
  /// in the test/ directory, but the template already includes
  /// `home_page_test.dart`. This default test file should be removed.
  Future<void> _cleanTests(String targetDir) async {
    final widgetTest = File(p.join(targetDir, 'test', 'widget_test.dart'));
    if (await widgetTest.exists()) {
      try {
        await widgetTest.delete();
        logger.detail(translations.create.removedWidgetTest);
      } on Object catch (e) {
        logger.detail(translations.create.removeWidgetTestFailed(error: e));
      }
    }
  }

  /// 删除 [targetDir]（目录不存在时静默跳过，删除失败只记日志不抛出）。
  ///
  /// 职责单一：只做删除，不判断该不该删。
  /// **是否有权删除由调用方决定** —— 仅当目录确认为本次命令创建的半成品时
  /// 才可调用；用户既有目录的场景由 [DirExistsException] 分支拦截，不会走到这里。
  ///
  /// Deletes [targetDir] (silently skips when absent, logs deletion failures).
  ///
  /// Single responsibility: it only deletes and never decides whether deletion
  /// is allowed. Callers must ensure the directory was created by this run;
  /// pre-existing user directories are handled by the [DirExistsException]
  /// branch and never reach this method.
  Future<void> _cleanupOnFailure(String targetDir) async {
    final dir = Directory(targetDir);
    if (await dir.exists()) {
      try {
        await dir.delete(recursive: true);
        logger.detail(translations.create.cleanedFailedDir);
      } on Object catch (e) {
        logger.detail(translations.create.cleanupFailedDir(error: e));
      }
    }
  }

  // ---------------------------------------------------------------------------
  // Default runners
  // ---------------------------------------------------------------------------

  /// 默认的 flutter create 执行器 / Default flutter create runner
  Future<int> _flutterCreate(
    String projectRoot, {
    String? projectName,
    String? org,
  }) {
    final args = ['create', '.'];
    if (projectName != null) {
      args.addAll(['--project-name', projectName]);
    }
    if (org != null) {
      args.addAll(['--org', org]);
    }
    return processRunner.run(
      'flutter',
      args,
      workingDirectory: projectRoot,
      showLive: logger.level == Level.verbose,
      runInShell: true,
    );
  }

  /// 默认的 flutter pub get 执行器 / Default flutter pub get runner
  Future<int> _flutterPubGet(String projectRoot) {
    return processRunner.run(
      'flutter',
      ['pub', 'get'],
      workingDirectory: projectRoot,
      showLive: logger.level == Level.verbose,
      runInShell: true,
    );
  }

  /// 默认的 flutter gen-l10n 执行器 / Default flutter gen-l10n runner
  Future<int> _flutterGenL10n(String projectRoot) {
    return processRunner.run(
      'flutter',
      ['gen-l10n'],
      workingDirectory: projectRoot,
      showLive: logger.level == Level.verbose,
      runInShell: true,
    );
  }
}
